version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Assuming your React app runs on port 80 inside the container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Assuming your backend service listens on port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
