version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
