version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"  # port 80 of the host server which accepts tcp -> 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Assuming your backend service listens on port 8000
    networks:
      - app-network
    volumes:
      - upload_data:/app/Uploads
      - embedding_data:/app/Embeddings

volumes:
  upload_data: {}
  embedding_data: {}
  
networks:
  app-network:
    driver: bridge

